import {mountCreditSlider} from './credit-slider.js';
import {mountAIHero} from '../components/reconstructed/ai-input-hero.js';
import {mountTabs} from '../components/reconstructed/expandable-tabs.js';
import {mountWorkspaces} from '../components/reconstructed/workspaces.js';
import {mountShiningText} from '../components/reconstructed/shining-text.js';
import {icon,el,button} from '../components/reconstructed/shared.js';
const $=s=>document.querySelector(s), content=$('#content');
$('.skip').onclick=e=>{e.preventDefault();content.focus()};
const nav=[['assistant','Assistente','home'],['ads','Anúncios','box'],['inbox','Atendimento','chat'],['agents','Agentes','bell'],['stores','Lojas','box'],['credits','Créditos','plus'],['settings','Configurações','settings'],['support','Suporte','chat']];
const fallback={mode:'local_preview',authenticated:false,capabilities:{execution:false,billing:false,auth:false},agents:[{id:'publication',name:'Publicação',role:'Criação e gestão de anúncios',successes:null,failures:null,autonomy:'approval_required',specialists:[{name:'Foto',role:'Imagens do produto'},{name:'Copy',role:'Títulos e descrições'},{name:'Preço',role:'Regras de precificação'}]},{id:'service',name:'Atendimento',role:'Conversas com compradores',successes:null,failures:null,autonomy:'approval_required',specialists:[]}],models:[{id:'default',name:'Padrão Steve',description:'Servidor Steve · não conectado'},{id:'personal',name:'Conta pessoal',description:'Seu provedor · não conectado'},{id:'local',name:'Modelo local',description:'Sua máquina · não conectado'}],stores:[],tasks:[],plans:[]};
let data=fallback,unmount=[],modelPicker,selectedModel='default',serverDrafts=[];
function read(key,def){try{return JSON.parse(localStorage.getItem(key))??def}catch{return def}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{toast('Armazenamento indisponível. O rascunho não foi salvo.');return false}}
let drafts=read('steve.app.drafts.v1',[]);if(!Array.isArray(drafts))drafts=[];
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,4500)}
function node(tag,cls,text){return el(tag,cls,text)}
function action(text,fn,cls='primary'){const b=button(text);b.className=cls;b.onclick=fn;return b}
function heading(kicker,title,sub){content.append(node('div','eyebrow',kicker),node('h1','',title),node('p','sub',sub))}
function empty(parent,text){parent.append(node('div','empty',text))}
function saveDraft(text,kind='pedido',title=''){const draft={id:crypto.randomUUID(),text,kind,title,model:selectedModel,createdAt:new Date().toISOString()};const next=[draft,...drafts].slice(0,100);if(write('steve.app.drafts.v1',next)){drafts=next;toast('Rascunho salvo neste dispositivo. Nenhuma execução disparada.')}if(data.draftToken)persistDraft(draft);return draft}
async function persistDraft(draft){try{const r=await fetch('/api/app/drafts',{method:'POST',headers:{'Content-Type':'application/json','X-Steve-Local-Token':data.draftToken},body:JSON.stringify({text:(draft.title?draft.title+'\n':'')+draft.text,model:draft.model,requestKey:draft.id})});if(!r.ok)throw Error();const result=await r.json();serverDrafts=[result.draft,...serverDrafts.filter(x=>x.id!==result.draft.id)];toast('Rascunho também salvo no serviço local. Nenhuma execução disparada.')}catch{toast('Rascunho salvo no navegador; o serviço local não confirmou a cópia.')}}
function renderDrafts(parent,kind){const items=kind?drafts.filter(d=>d.kind===kind):drafts;const head=node('div','section-head');head.append(node('h2','','Seus rascunhos'),node('span','pill',`${items.length} neste dispositivo`));parent.append(head);if(!items.length){empty(parent,'Seu próximo pedido começa aqui. Os rascunhos ficam salvos apenas neste dispositivo.');return}for(const d of items){const row=node('div','draft-row'),body=node('p','',d.title||d.text);body.append(node('small','',`${d.kind} · ${new Date(d.createdAt).toLocaleDateString('pt-BR')} · aguardando envio`));const remove=action('Excluir',()=>{const next=drafts.filter(x=>x.id!==d.id);if(write('steve.app.drafts.v1',next)){drafts=next;render()}},'secondary');row.append(body,remove);parent.append(row)}}
function assistant(){const hero=node('section');content.append(hero);const mounted=mountAIHero(hero,{onSubmit:text=>{saveDraft(text);queueMicrotask(()=>hero.querySelector('.s-request-status').textContent='Rascunho salvo neste dispositivo. A execução ainda não está conectada.');draftArea.replaceChildren();renderDrafts(draftArea)}});unmount.push(mounted);hero.querySelector('.s-brand').href='../';hero.querySelector('button[type=submit]').setAttribute('aria-label','Salvar pedido como rascunho');hero.querySelector('textarea').placeholder='O que vamos preparar para a sua loja?';const shortcuts=node('div','shortcuts');for(const [title,desc,route] of [['Preparar um anúncio','Produto, imagens, preço e revisão.','ads'],['Organizar o atendimento','Tom de voz e limites das respostas.','inbox']]){const b=action('',()=>location.hash=route,'shortcut');b.append(node('strong','',title+' ↗'),node('small','',desc));shortcuts.append(b)}content.append(shortcuts);const draftArea=node('section');content.append(draftArea);renderDrafts(draftArea);if(serverDrafts.length){content.append(node('h2','','Rascunhos no serviço local'));for(const d of serverDrafts){const row=node('div','draft-row');const p=node('p','',d.text);p.append(node('small','','Persistido no servidor local · não executado'));row.append(p);content.append(row)}}}
function ads(){heading('PUBLICAÇÃO','Do produto ao anúncio.','Prepare o escopo. Fotos, copy e preço entram em etapas especializadas, com sua aprovação.');const form=node('form','form card'),label=node('label','','Nome do produto'),title=node('input');title.required=true;title.maxLength=160;label.append(title);const detail=node('label','','Contexto do anúncio'),text=node('textarea');text.required=true;text.maxLength=4000;text.placeholder='Características, diferenciais, estoque, limites de preço e referências…';detail.append(text);const submit=action('Salvar rascunho',()=>{});submit.type='submit';form.append(label,detail,node('small','','Não inclua senhas ou chaves. Publicação e conexão das lojas ainda não estão habilitadas.'),submit);form.onsubmit=e=>{e.preventDefault();saveDraft(text.value,'anúncio',title.value);render()};content.append(form,node('div','sub'));renderDrafts(content,'anúncio')}
function inbox(){heading('ATENDIMENTO','A conversa começa com contexto.','Defina como sua marca conversa. As respostas aos compradores só serão ativadas depois de conectar a loja.');const form=node('form','form card'),label=node('label','','Regras de atendimento'),text=node('textarea');text.value=read('steve.app.service.v1','');text.placeholder='Tom de voz, prazos, dúvidas comuns e quando chamar uma pessoa…';text.maxLength=8000;label.append(text);const submit=action('Salvar orientações',()=>{});submit.type='submit';form.append(label,submit);form.onsubmit=e=>{e.preventDefault();if(write('steve.app.service.v1',text.value))toast('Orientações salvas neste dispositivo.')};content.append(form,node('h2','','Conversas'));empty(content,'Nenhuma loja conectada. As conversas reais aparecerão aqui quando a integração estiver ativa.')}
function agents(){heading('ESPECIALISTAS','Seu time, em detalhe.','Experiência vem de execuções verificadas. Autonomia é uma permissão sua.');const wrap=node('div','table-wrap'),table=node('table');table.innerHTML='<caption class="sr-only">Agentes disponíveis</caption><thead><tr><th scope="col">Agente / experiência</th><th scope="col">Especialidade</th><th scope="col">Autonomia</th></tr></thead>';const tbody=node('tbody');for(const a of data.agents){const tr=node('tr'),td=node('td'),link=node('a','agent-link');link.href='#agents/'+encodeURIComponent(a.id);const detail=node('div');detail.append(node('strong','',a.name));const xp=node('div','xp'),fill=node('span');const known=Number.isFinite(a.successes)&&Number.isFinite(a.failures)&&a.successes+a.failures>0;fill.style.width=known?`${a.successes/(a.successes+a.failures)*100}%`:'0%';xp.append(fill);detail.append(xp,node('small','',known?`${a.successes} acertos · ${a.failures} falhas`:'Sem histórico verificado'));link.append(node('span','avatar',a.name[0]),detail);td.append(link);tr.append(td,node('td','',a.role||a.scope),node('td','','Aprovação necessária'));tbody.append(tr)}table.append(tbody);wrap.append(table);content.append(wrap)}
function agentDetail(id){const agent=data.agents.find(a=>a.id===id);if(!agent){heading('AGENTES','Agente não encontrado.','Volte à lista para escolher um especialista disponível.');content.append(action('Ver agentes',()=>location.hash='agents'));return}heading('ESPECIALISTAS',agent.name,agent.role||agent.scope);const group=node('section','card'),head=node('div','chat-head'),people=node('div','facepile');head.append(node('span','','# equipe de '+agent.name.toLowerCase()));const staff=agent.specialists||[];for(const s of staff)people.append(node('span','avatar',(typeof s==='string'?s:s.name||'?')[0]));head.append(people);group.append(head);if(!staff.length)empty(group,'A equipe especializada será exibida quando estiver vinculada ao agente.');for(const s of staff){const item=typeof s==='string'?{name:s,role:'Especialista do escopo'}:s;const row=node('div','chat-entry'),body=node('div');body.append(node('strong','',item.name),node('p','',item.role||item.description||'Especialista do escopo'));row.append(node('span','avatar',item.name[0]),body);group.append(row)}group.append(node('h2','','Histórico de execução'));empty(group,'Ainda não há eventos de execução verificados para esta conta.');content.append(group,node('p','sub','O agente não ganha permissão de publicação automaticamente com a experiência. A concessão precisa ser explícita por loja e tipo de tarefa.'))}
function stores(){heading('CONEXÕES','Cada loja, no seu lugar.','Contas separadas, contexto preservado e permissões visíveis.');const grids=node('div','split');for(const name of ['Mercado Livre','Shopee','TikTok Shop','Outros marketplaces']){const card=node('div','card');card.append(node('span','pill','Não conectado'),node('h2','',name),node('p','sub','Conexão ainda não habilitada nesta versão.'));const b=action('Conectar loja',()=>{});b.disabled=true;card.append(b);grids.append(card)}content.append(grids,node('p','sub','Nenhum perfil de navegador, cookie ou senha é importado por esta prévia.'))}
async function quote(amount,status){status.textContent='Consultando cotação…';try{const r=await fetch('/api/app/quotes',{method:'POST',headers:{'Content-Type':'application/json','X-Steve-Local-Token':data.draftToken||''},body:JSON.stringify({amount,currency:'BRL'})});if(!r.ok)throw Error();const q=await r.json();status.textContent=Number.isFinite(q.credits)?`${q.credits} créditos · cotação do servidor`:'Cotação indisponível.'}catch{status.textContent='Tabela de créditos e pagamento ainda não configurados. Nenhum valor foi cobrado.'}}
function credits(){heading('CONSUMO','Mais espaço para executar.','Consulte o valor antes de comprar. A tabela de consumo e a cobrança ainda precisam ser habilitadas.');const card=node('section','card'),amounts=node('div','quote-amounts'),left=node('span'),right=node('span','','—');let amount=100;const amountText=node('strong','','R$ 100');left.append(node('small','','VOCÊ INVESTE'),amountText);right.prepend(node('small','','VOCÊ RECEBE EM CRÉDITOS'));amounts.append(left,right);card.append(amounts);const track=node('div');card.append(track);unmount.push(mountCreditSlider(track,{value:100,onChange:value=>{amount=value;amountText.textContent=amount.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}}));const status=node('p','sub','A quantidade de créditos depende da tabela aprovada no servidor.');status.setAttribute('role','status');card.append(action('Consultar cotação',()=>quote(amount,status)),status);const offer=node('section','card offer');offer.append(node('span','eyebrow','BOAS-VINDAS'),node('h2','','Seu benefício de primeiro acesso'),node('p','sub','A oferta aparecerá aqui depois do login, se estiver disponível para sua conta. O prazo é confirmado pelo servidor.'),node('span','pill','Aguardando autenticação'));content.append(card,offer)}
function settings(){heading('PREFERÊNCIAS','Do seu jeito.','O modelo escolhido é uma preferência. A disponibilidade depende da conexão real.');const quick=node('div','actions');for(const [route,label] of [['stores','Lojas'],['credits','Créditos'],['support','Suporte']]){const a=node('a','secondary',label);a.href='#'+route;quick.append(a)}quick.style.marginBottom='22px';content.append(quick);for(const m of data.models){const card=node('div','card');card.style.marginBottom='12px';card.append(node('h2','',m.name),node('p','sub',m.description),node('span','pill','Não conectado'));content.append(card)}content.append(node('p','sub','Padrão: processamento no servidor Steve. Conta pessoal: provedor autorizado com suas condições de API. Local: requer sua máquina disponível. Não existe troca silenciosa entre modelos.'),action('Aparência: alternar tema',()=>setTheme(document.body.dataset.theme==='dark'?'light':'dark'),'secondary'))}
function support(){heading('AJUDA','Contexto para resolver.','Prepare sua solicitação. O envio ao suporte será liberado com a conexão da sua conta.');const form=node('form','form card'),label=node('label','','Descreva o que aconteceu'),text=node('textarea');text.required=true;text.maxLength=4000;text.placeholder='O que você tentou fazer e o que aconteceu?';label.append(text);const submit=action('Salvar solicitação',()=>{});submit.type='submit';form.append(label,node('small','','Não há atendimento humano ou agente conectado nesta prévia.'),submit);form.onsubmit=e=>{e.preventDefault();saveDraft(text.value,'suporte');render()};content.append(form,node('div','sub'));renderDrafts(content,'suporte')}
function render(){unmount.forEach(x=>x.destroy());unmount=[];content.replaceChildren();const [route,id]=location.hash.slice(1).split('/');const key=route||'assistant';$('#pageName').textContent=nav.find(x=>x[0]===key)?.[1]||'Página não encontrada';document.querySelectorAll('.navlink').forEach(a=>{const active=a.hash==='#'+key;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});if(key==='agents'&&id){let decoded=id;try{decoded=decodeURIComponent(id)}catch{}agentDetail(decoded);}else if(({assistant,ads,inbox,agents,stores,credits,settings,support})[key])({assistant,ads,inbox,agents,stores,credits,settings,support})[key]();else{heading('404','Esse caminho ainda não existe.','Retorne ao seu assistente.');content.append(action('Voltar ao início',()=>location.hash='assistant'))}}
for(const [id,label,ico] of nav){const a=node('a','navlink');a.href='#'+id;a.innerHTML=icon(ico);a.append(node('span','',label));$('#sidebarNav').append(a)}
mountTabs($('#mobileTabs'),{items:nav.filter(x=>['assistant','ads','inbox','agents','settings'].includes(x[0])).map(([id,label,icon])=>({id,label,icon})),onChange:({id})=>location.hash=id});
$('#newTask').onclick=()=>{location.hash='assistant';if(location.hash==='#assistant')render();requestAnimationFrame(()=>content.querySelector('textarea')?.focus())};
const themeMedia=matchMedia('(prefers-color-scheme: dark)');let theme=read('steve.app.theme','dark');function setTheme(value){theme=value;write('steve.app.theme',value);document.body.dataset.theme=value==='system'?(themeMedia.matches?'dark':'light'):value;document.querySelectorAll('#theme button').forEach(b=>b.setAttribute('aria-checked',String(b.dataset.theme===value)))}
for(const [value,title,symbol] of [['system','Seguir sistema','▣'],['light','Tema claro','☀'],['dark','Tema escuro','☾']]){const b=action(symbol,()=>setTheme(value));b.className='';b.dataset.theme=value;b.setAttribute('role','radio');b.setAttribute('aria-label',title);$('#theme').append(b)}setTheme(theme);themeMedia.addEventListener('change',()=>setTheme(theme));
mountShiningText($('#stateText'),{text:'Prévia · aguardando conexões'});
function sphere(){let out='';for(let y=-8;y<=8;y++){for(let x=-15;x<=15;x++){const r=(x/15)**2+(y/8)**2;out+=r>1?' ':r>.86?'·':'.:░▒▓'[(Math.floor((Math.sqrt(1-r)+x/20)*5)+5)%5]}out+='\n'}$('#sphere').textContent=out}sphere();
window.addEventListener('hashchange',render);render();
async function boot(){try{const r=await fetch('/api/app/bootstrap',{headers:{Accept:'application/json'}});if(!r.ok)throw Error();const result=await r.json();if(!Array.isArray(result.agents)||!Array.isArray(result.models))throw Error();data={...fallback,...result};if(data.draftToken){const saved=await fetch('/api/app/drafts',{headers:{'X-Steve-Local-Token':data.draftToken}});if(saved.ok)serverDrafts=(await saved.json()).drafts||[]}$('#connection').textContent='Serviço local conectado · rascunhos persistentes · execução, login e pagamentos indisponíveis.'}catch{$('#connection').textContent='Sem conexão com o serviço · você pode preparar rascunhos neste dispositivo.'}modelPicker?.destroy();modelPicker=mountWorkspaces($('#modelPicker'),{items:data.models,onChange:m=>{selectedModel=m.id;toast('Preferência de modelo alterada. Conexão ainda pendente.')},onConfigure:()=>location.hash='settings'});render()}boot();
