import {request} from '../app/api.js';
const status=document.querySelector('#auth-status'),login=document.querySelector('#login'),register=document.querySelector('#register-panel');let csrfToken='',available=false,busy=false;
function message(text,error=false){status.textContent=text;status.classList.toggle('auth-error',error)}
function switchMode(signup){const password=document.querySelector('#new-password');if(password){password.minLength=12;password.maxLength=128;}register.hidden=!signup;login.hidden=signup;document.querySelector('.providers').hidden=signup;document.querySelector('.divider').hidden=signup;document.querySelector('.signup').hidden=signup;document.querySelector('.otp-panel').hidden=signup;document.querySelector('.login-form h2').textContent=signup?'Seu próximo passo.':'Entre no Steve.';document.querySelector(signup?'#register-name':'#email').focus()}
document.querySelector('#open-register').onclick=()=>switchMode(true);document.querySelector('#back-login').onclick=()=>switchMode(false);
document.querySelector('#toggle-password').onclick=e=>{const input=document.querySelector('#password');const show=input.type==='password';input.type=show?'text':'password';e.currentTarget.textContent=show?'Ocultar':'Mostrar';e.currentTarget.setAttribute('aria-pressed',String(show));e.currentTarget.setAttribute('aria-label',show?'Ocultar senha':'Mostrar senha')};
for(const button of document.querySelectorAll('[data-auth]'))button.onclick=()=>message(`${button.dataset.auth}: integração ainda não habilitada. Nenhum dado foi enviado.`);
async function submit(form,path,body){if(busy)return;if(!available){message('O serviço de identidade está indisponível. Nenhuma credencial foi salva.',true);return}busy=true;const submit=form.querySelector('[type=submit]');submit.disabled=true;message('Conferindo sua conta…');try{const result=await request(path,{method:'POST',csrfToken,body});if(result.authenticated===false){message('A conta foi recebida, mas o servidor ainda não confirmou uma sessão.',true);return}const session=await request('/api/auth/session');if(!session.authenticated)throw Error('O servidor não confirmou uma sessão. Tente entrar novamente.');location.assign('../app/')}catch(error){message(error.status===401?'E-mail ou senha incorretos.':error.message||'Não foi possível entrar. Tente novamente.',true)}finally{busy=false;submit.disabled=false}}
login.onsubmit=e=>{e.preventDefault();submit(login,'/api/auth/login',{email:document.querySelector('#email').value.trim(),password:document.querySelector('#password').value})};
register.onsubmit=e=>{e.preventDefault();submit(register,'/api/auth/register',{name:document.querySelector('#register-name').value.trim(),email:document.querySelector('#register-email').value.trim(),password:document.querySelector('#new-password').value})};
const retry=document.createElement('button');retry.type='button';retry.className='text-button auth-retry';retry.textContent='Tentar conectar novamente';retry.hidden=true;status.after(retry);async function connect(){retry.hidden=true;message('Conectando ao serviço de identidade…');try{const bootstrapPromise=request('/api/app/bootstrap',{signal:AbortSignal.timeout(10000)}).catch(()=>null);const session=await request('/api/auth/session',{signal:AbortSignal.timeout(10000)});csrfToken=session.csrfToken||'';if(session.authenticated){location.replace('../app/');return}const bootstrap=await bootstrapPromise;if(!bootstrap)throw Error('O serviço demorou para responder.');csrfToken=bootstrap.csrfToken||csrfToken;available=bootstrap.capabilities?.auth===true;message(available?'Entre com e-mail e senha ou crie sua conta.':'O serviço de identidade ainda não está habilitado. Nenhuma credencial será enviada.');retry.hidden=available}catch{available=false;message('Não foi possível conectar agora. Tente novamente; seus campos permanecem preenchidos.',true);retry.hidden=false}}retry.onclick=connect;connect();
